### ISSUE TITLE
Will it work if I update the offsets?

### ISSUE THREAD

**Issue by HeroofHell** [Griizz/Fortnite-Hack#19]
I just have a quick question which is: will this project work if I just update the offsets and the other stuff and add a bit of junkcode. Or do I have to make ither changes

**Comment by Kuhicop** [comment]
It takes more time to get an answer than test it yourself.
I will answer your question with a small example.
If you have a cheat and the game makes an update, depending on what things they change you may be affected or not.
While dealing with memory it depends because some regions are loaded when launching the game, some others when connecting and others while playing.
So, if the devs made an update adding content to that "loads" then your memory may change as the "region" is not the same it was before adding new content.
For example if nearby players start at memory 0x0450 and nearby player health starts at 0x0451 if something is added in that patch between 0x0450 and 0x0451, probbably the new value will be added in 0x0451 and the health address will be moved to 0x0452.
This is possible, but not normal, because the typical programming "protocol" or "education" shows us to mantain an order, and if we dig further, normally this kind of datas are structures which are stored by nodes in order, so when you find the first node of the structure, normally you will find all values each 4 bytes after your actual value.

I didn't test this software but as I said above, should work or should be easy to make it work.
All of this thinking there are no additional security measures, like this dll had been patched. If you don't face that problem, should be ok.
